#!/bin/bash

ufw reset
ufw allow in 	"WWW Secure"
ufw allow in 	"WWW"
ufw allow in 	"DNS"
ufw allow in	"SSH"
ufw allow in	9050

ufw allow out 	"WWW Secure"
ufw allow out 	"WWW"
ufw allow out 	"DNS"
ufw allow out	"SSH"
ufw allow out 	9050
ufw enable
