#!/bin/bash

ufw reset
ufw default deny outgoing
ufw default deny incoming
ufw allow in 	"WWW Secure"
ufw allow in 	"DNS"
ufw allow out 	"WWW Secure"
ufw allow out 	"DNS"
ufw allow in	"SSH"
ufw allow out	"SSH"
ufw allow in	9050
ufw allow out 	9050
ufw enable
